#!/usr/bin/env bash

# Required for Linux Mint installs
if command -v /usr/bin/snap &> /dev/null
then
  echo "** SNAP installed"
else
  rm /etc/apt/preferences.d/nosnap.pref
  apt update
  apt install snapd
fi