#!/usr/bin/env bash

# Tested on Ubuntu 21.04
# Run with sudo ./install_apps

source $(dirname $0)/common/enable_snap

apt install -y emacs mu4e isync ripgrep

# Password manager
apt install -y pass qtpass upass keepassxc

# Tools
apt install -y terminator screen htop mg zsh gkrellm aptitude synapse inxi neofetch apt-file pigz
apt-file update

# Remote assistance/work
apt install -y x2goclient
source $(dirname $0)/common/install_thinlinc

# graphics
apt install -y gpick cheese
snap install ksnip

# internet
apt install -y filezilla torbrowser-launcher chromium-browser ktorrent

# other
apt install -y solaar redshift-gtk gparted gkrellm grub-customizer clamav
snap install rpi-imager

# backup/sync
apt install -y timeshift syncthing dropbox
source $(dirname $0)/common/install_duplicati

# multimedia
apt install -y kodi kodi-pvr-hts steam vlc handbrake
source $(dirname $0)/common/install_xeoma

# Office
apt install -y paperwork-gtk pdfarranger
snap install xournalpp

# chat
snap install zoom-client skype teams discord telegram-desktop signal-desktop whatsapp-app
